name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'  # Or 3.10/3.12 based on your project

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run mypy (type checking)
      run: |
        mypy .

    - name: Run black (formatting check)
      run: |
        black --check .

    - name: Run tests (pytest)
      run: |
        pytest
